spring:
  application:
    name: "Just-Chill"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/justchill"
    username: "dark"
    password: "dark"


  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
